### PR TITLE
Rename _build to _jbuild

### PR DESCRIPTION
**Pull request by rgrinberg**
_build is already quite overloaded.

This was a search and replace job. Would probably be better if this was just a
constant somewhere

### CODE REVIEW

**Comment by diml** [comment]
Indeed. I just added a `Config` module, maybe you could add it there?

**Comment by diml** [comment]
I might have introduced a few more `_build` as I reworked the artifact resolution

**Comment by rgrinberg** [comment]
Config will not work without further changes. Otherwise it will create a circular dependency with Path.

**Comment by diml** [comment]
Damn, indeed. I guess it will need to go into `Path` directly

**Pull request merged**
