### PR TITLE
Ppx rewriter tests

### PR DESCRIPTION
**Pull request by rgrinberg**
I wanted to write some ppx rewriter tests because the linting PR was going to touch this stuff a little bit and I've come across this little issue. I'm not sure how to pass custom driver arguments when I use ppx_driver as my driver. See the last failing test.

### CODE REVIEW

**Comment by diml** [comment]
Hmm, yh maybe this is not supported. You can always use `Ppx_driver.add_arg`

**Comment by rgrinberg** [comment]
Is it possible to fix ppx_driver to support this? It's a bit of an annoying situation as some ppx's do use these arguments to good effect (bisect_ppx for one)

**Comment by diml** [comment]
Yes, we just need to add a function in `Migrate_parsetree.Driver` to get the list of registered arguments

**Comment by rgrinberg** [comment]
OK I disabled the test because I can't make it fail consistently since it depends on the version of driver. Will revive it once ppx_driver is fixed (will make the appropriate issues shortly).

**Pull request merged**
