### PR TITLE
Jbuilder exec rebuilt if possible option

### LINKED ISSUE #317: jbuilder exec should build its target before executing it
It was suggested in #152 that `$ jbuilder exec` should build (or rebuild) its target before executing it. However, diml noted that this should only work in "dev" mode. I.e. enabled via `--dev`.

### PR DESCRIPTION
**Pull request by rgrinberg**
This option turns out to be quite handy in practice. Been using it for the last day without major issues. I've elected to just make its own option for now because `--dev` seems like it would leave the user guessing. Maybe it's best to support both flags?

Fix #317

cc @copy

### CODE REVIEW

**Comment by rgrinberg** [comment]
Right now the only caveat with this PR is the error handling. In some cases, we know the path must exist locally in the build system, so a build error is more appropriate than a not found error.

**Comment by rgrinberg** [comment]
Thanks for clarifying @diml, I understand now. So I think it's just a matter of switch the flag to be `--no-build`. Unless anyone wants to argue this point, I will do that before soon enough. Comments about the implementation are welcome.

**Comment by rgrinberg** [comment]
I will also add the `--dev` option to `jbuilder exec` to at least give users the option to avoid this issue.

**Comment by rgrinberg** [comment]
@bobot @diml I've changed the default to build. --dev was already supported btw. But i added a test for it just in case.

**Comment by diml** [comment]
I had a quick look at the code, it looks fine to me. `resolve_targets'/resolve_targets` should be renamed `resolve_targets/resolve_targets_exn`.

In the test case, I would prefer if the first error was something like: `Program ./foo.exe isn't built yet, you need to build it first or remove the --no-build option`.

BTW, `resolve_targets` and the code for resolving executables is becoming a bit complicated. Now that we can give arbitrary requests to the build system, we could encode what this code is doing in the build arrow directly. This doesn't need to be done in this PR though, but we should keep it in mind if it becomes too complicated.

**Comment by rgrinberg** [comment]
> I had a quick look at the code, it looks fine to me. resolve_targets'/resolve_targets should be renamed resolve_targets/resolve_targets_exn.

Done.

> In the test case, I would prefer if the first error was something like: Program ./foo.exe isn't built yet, you need to build it first or remove the --no-build option

You only expect this to work for relative paths, right? Because to make it work in general, i.e. for things like `jbuilder exec foo` would require us to know if `foo` is installable. Which is possible, but we don't really have a convenient way to do it.

> BTW, resolve_targets and the code for resolving executables is becoming a bit complicated. Now that we can give arbitrary requests to the build system, we could encode what this code is doing in the build arrow directly. This doesn't need to be done in this PR though, but we should keep it in mind if it becomes too complicated.

+1

**Comment by diml** [comment]
> You only expect this to work for relative paths, right? Because to make it work in general, i.e. for things like jbuilder exec foo would require us to know if foo is installable. Which is possible, but we don't really have a convenient way to do it.

Well, we can test if `_build/install/default/bin/foo` is a target for instance. But we can leave that until we refactor `resolve_targets`. For instance we could add a function like this `Build_system`:

```ocaml
(** Returns the first file that the build system knows how to build *)
val find_buildable_target : t -> Path.t list -> Path.t option Future.t
```

then we'd do calls such as

```
Build_system.find_buildable_target ["_build/install/default/bin/foo"; "/usr/bin/foo"; ...]
```

That'd make the code a bit simpler overall I think.

**Comment by rgrinberg** [comment]
OK, so then there's no more work in this PR to be done if we should do the refactoring to improve the error message. I'll create the relevant ticket for this work on this PR is merged then.

**Comment by rgrinberg** [comment]
@diml i ended up implementing your error message improvement for local/absolute paths in jbuilder exec.

**Comment by diml** [comment]
OK, seems good

**Pull request merged**
