### PR TITLE
Cross Compilation [Rewritten History]

### PR DESCRIPTION
**Pull request by rgrinberg**
@diml this is my half hearted at rewriting the history. The result is completely fictitious, especially wrt attribution, but at least it looks pretty and every commit builds. I think this beats 1 squashed commit by a large margin, but perhaps even keeping the dirty history makes sense?

### CODE REVIEW

**Comment by diml** [comment]
Thanks, I'm happy to use this history

**Comment by diml** [comment]
@toots, can you try again with this branch?

**Comment by wokalski** [comment]
The docs only mention opam-cross-Windows and opam-cross-android. Is there a particular reason why opam-cross-ios is not supported ?

**Comment by rgrinberg** [comment]
It most likely works we just haven't tested it. Actually we haven't tested
Android either.

**Comment by whitequark** [comment]
The only issue with iOS I anticipate is the lack of dynlink, does jbuilder handle that correctly?

**Comment by rgrinberg** [comment]
Jbuilder supports building libs without dynlink, and it either lets you disable dynlink for a package manually or it tries to discover if the compiler supports dynlink by checking if `dynlink.cmxa` exists in the switch. Will that check work for opam-cross-ios?

**Comment by whitequark** [comment]
The latter should work!

**Comment by toots** [comment]
Any idea if this error could be caused by the changes in `jbuilder`? The PR is only updating `jbuilder` and it built fine before..
```
#=== ERROR while installing pcre-windows.7.3.4 ================================#
# opam-version         1.2.2
# os                   linux
# command              env PKG_CONFIG_PATH=/usr/src/mxe/usr/x86_64-w64-mingw32.static/lib/pkgconfig jbuilder-windows build -p pcre -j 4 -x windows
# path                 /home/opam/.opam/4.04.0/build/pcre-windows.7.3.4
# compiler             4.04.0
# exit-code            1
# env-file             /home/opam/.opam/4.04.0/build/pcre-windows.7.3.4/pcre-windows-8-6a72f2.env
# stdout-file          /home/opam/.opam/4.04.0/build/pcre-windows.7.3.4/pcre-windows-8-6a72f2.out
# stderr-file          /home/opam/.opam/4.04.0/build/pcre-windows.7.3.4/pcre-windows-8-6a72f2.err
### stderr ###
# /usr/src/mxe/usr/x86_64-w64-mingw32.static/include/string.h:89:9: error: declaration for parameter 'strncpy' but no such parameter
# [...]
# /usr/src/mxe/usr/x86_64-w64-mingw32.static/include/string.h:84:9: error: declaration for parameter 'strlwr_l' but no such parameter
#    char *strlwr_l(char *_String,_locale_t _Locale) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
#          ^
# pcre_stubs.c:862:1: error: expected '{' at end of input
#  { return Val_bool(pcre_config_int(PCRE_CONFIG_STACKRECURSE)); }
#  ^
# pcre_stubs.c:862:1: warning: control reaches end of non-void function [-Wreturn-type]
#  { return Val_bool(pcre_config_int(PCRE_CONFIG_STACKRECURSE)); }
#  ^
```

**Comment by rgrinberg** [comment]
I don't think so. Here's the only the difference:

```
diff --git a/src/findlib.ml b/src/findlib.ml
index 2a287c9..ca84456 100644
--- a/src/findlib.ml
+++ b/src/findlib.ml
@@ -55,6 +55,7 @@ module Rule = struct
     Preds.is_subset preds ~subset:t.preds_required &&
     not (Preds.intersects preds t.preds_forbidden)
 
+
   let make (rule : Meta.rule) =
     let preds_required, preds_forbidden =
       List.partition_map rule.predicates ~f:(function
diff --git a/src/import.ml b/src/import.ml
index 135575a..0308ad3 100644
--- a/src/import.ml
+++ b/src/import.ml
@@ -78,11 +78,6 @@ module List = struct
       max acc (String.length (f x)))
 
   let longest l = longest_map l ~f:(fun x -> x)
-
-  let assoc_opt e l =
-    match List.assoc e l with
-    | e -> Some e
-    | exception Not_found -> None
 end
 
 module Hashtbl = struct
diff --git a/src/sexp.ml b/src/sexp.ml
index f63e9f6..53bc05d 100644
--- a/src/sexp.ml
+++ b/src/sexp.ml
@@ -450,7 +450,7 @@ module Of_sexp = struct
       | Record x -> x.name
   end
   module C = Constructor_spec
-  
+
   let cstr_loc name args make =
     C.Tuple { name; args; make; rest = No_rest }
   let cstr_rest_loc name args rest make =
diff --git a/src/sexp.mli b/src/sexp.mli
index e820b53..4c2401b 100644
--- a/src/sexp.mli
+++ b/src/sexp.mli
@@ -99,8 +99,8 @@ module Of_sexp : sig
     -> ('a -> 'b, 'c) Constructor_args_spec.t
 
   val cstr : string -> ('a, 'b) Constructor_args_spec.t -> 'a -> 'b Constructor_spec.t
-  val cstr_rest :
-    string
+  val cstr_rest
+    :  string
     -> ('a, 'b list -> 'c) Constructor_args_spec.t
     -> 'b t
     -> 'a
```

You can try the old branch and see if there's a difference.

**Comment by rgrinberg** [comment]
I merged the branch because it's really unlikely this is caused by any of the changes above. We can address the problem in a later PR if it's really a fault introduced here.

**Comment by diml** [comment]
> The docs only mention opam-cross-Windows and opam-cross-android. Is there a particular reason why opam-cross-ios is not supported ?

@wokalski, no reason. I just didn't see the opam-cross-ios repository. I listed the repositories explicitly to be clear about what jbuilder was expected to work with. I see that these have now moved to a new organization so I'll update the doc.

**Comment by diml** [comment]
I'm not sure, @bobot, do you remember the status of #23?

**Comment by diml** [comment]
I updated the doc BTW: https://github.com/ocaml/dune/pull/434

**Pull request merged**
