### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by rgrinberg**
I'd like to make a release once the odoc PR is merged. @diml any objections?

### CODE REVIEW

**Comment by diml** [comment]
Nope, but I heard that jbuilder doesn't build with OCaml trunk, we should have a quick look before to see if it's easy to fix

**Comment by rgrinberg** [comment]
Hmm, I just built it with trunk now.

**Comment by diml** [comment]
Ok, it's fine then

**Comment by rgrinberg** [comment]
I'll merge this now, since the odoc wil be ready in a couple of weeks or so.

**Pull request merged**
