### PR TITLE
Availability of "num" depends on the OCaml version

### PR DESCRIPTION
**Pull request by xclerc**
(originally reported by @trefis)

When trying to link with `nums` in OCaml 4.06, the user gets
an unexpected error message if `ocamlfind` is not present,
because `jbuilder` hardcodes (in `src/meta.ml`) the set of
package that ship with the OCaml distribution.

This PR conditionally includes `nums` in the set, by testing
if the related archive file is present.

### CODE REVIEW

**Comment by diml** [comment]
Can't we just add an `exist_if` field?

**Comment by xclerc** [comment]
Indeed. It has the nice property that the patch is reduced to a one-liner.
However, the user gets a slightly different error message metionning a
"hidden" library.

**Comment by diml** [comment]
Hmm, yh that's not great. Let's keep it like this then.

I'd just like for the result of `builtins ~stdlib_dir` to be cached inside the `Findlib.t` value, to avoid recomputing it every time we need it. Do you mind making this change?

**Comment by xclerc** [comment]
Just to be sure: we are talking about making `Meta.builtins` lazy, right?

**Comment by diml** [comment]
Sorry, I meant to keep your original patch and store the result of `builtins ~stdlib_dir` inside `Findlib.t`. Then `Findlib.builtins` becomes:

```
val builtins : t -> ...
```

**Comment by xclerc** [comment]
Did the suggested change, and added a comment explaining
why we decided not to use an "exists_if" variable.

**Comment by diml** [comment]
Thanks, looks good

**Pull request merged**
