### PR TITLE
Run bash through /usr/bin/env

### PR DESCRIPTION
**Pull request by sg2342**

### CODE REVIEW

**Comment by diml** [comment]
Can you provide some motivation for this patch? BTW I removed the `bash` function in `src/gen_rules.ml` as it was just some leftover dead code

**Comment by hannesm** [comment]
@diml I'd suspect this change is needed to run jbuilder on any [posix](http://standards.ieee.org/develop/wg/POSIX.html) system, not only those flavours which assume that a shell is a bourne shell - i.e. there are unix systems out there which do not contain any `/bin/bash`.

**Comment by sg2342** [comment]
@diml 
My motivation was that `opam install bin_prot` failed because it depens on `ppx_ast` and  https://github.com/janestreet/ppx_ast/blob/master/src/jbuild#L29 as well as https://github.com/janestreet/ppx_ast/blob/master/src/jbuild#L34 did not work on my platform.

Depending on GNU Bourne-Again SHell for build seems o.k. - esp. since some Linux distributions ship system shells `/bin/sh` that are not POSIX compliant (Debian).

But hard coding the path to the executabel is not.

**Comment by diml** [comment]
Ok, i guess that looking up bash in the `PATH` should be fine as well, i.e. we don't need to wrap it with `/usr/bin/env`?

It seems that bin_prot doesn't make use of the ppx rewriter, i'll look into removing this dependency

**Comment by diml** [comment]
I implemented the lookup in the PATH. Hopefully that should fix this problem.

I looked at removing the ppx dependency on bin_prot. There are a few uses so it's not completely straightforward, however we can switch it do `[@@deriving_inline ...]` if the ppx dependency is a problem.

**Comment by sg2342** [comment]
works for me. thank you.

**Comment by mato** [comment]
Found this issue while diagnosing latest MirageOS dependencies (`ppx_ast` specifically) failing to install on FreeBSD. Would it be possible to cut a new release of jbuilder with this fix sooner rather than later? Note that you will also want a `depext` on `bash` to ensure that it's actually installed. (/cc @hannesm)

**Comment by diml** [comment]
Sure, I'll do a release today. jbuilder itself doesn't require bash, it's only packages that explicitly use `(bash ...)` that require it. I can do a release of ppx_ast without bash if it's the only dependency that uses bash

**Comment by diml** [comment]
PR submitted: https://github.com/ocaml/opam-repository/pull/8843

**Pull request closed without merging**
