### PR TITLE
Add a toplevel html index to the docs

### PR DESCRIPTION
**Pull request by samoht**
See http://mirage.github.io/ocaml-git/index.html for an example of what is generated. It's really minimal at the moment but that's better than nothing.

### CODE REVIEW

**Comment by samoht** [comment]
Windows CI is broken?

**Comment by dra27** [comment]
Just waiting for #226 to run through Travis (FWIW) then I'll merge it - either force push or rebase and AppVeyor should clear.

There've been problems in the last few days with AppVeyor downloading 7zip from chocolatey, but it's not really necessary since Cygwin's unzip is preinstalled...

**Comment by dra27** [comment]
(#226 now merged)

**Comment by samoht** [comment]
Thanks, rebased.

**Comment by dra27** [comment]
LGTM - @rgrinberg?

**Comment by rgrinberg** [comment]
Looks good. Thanks @samoht

**Pull request merged**
