### PR TITLE
Build documentation for non-public libraries

### PR DESCRIPTION
**Pull request by MiloDavis**
Currently, Jbuilder doesn't build documentation for non-public libraries. It would be nice if this was possible. This PR makes it the default, which may not be a good long-term decision. I'm happy to make any changes to improve the ergonomics and not break existing use cases.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Am I correct to state that the private libraries will not be included in the top level generated index? So the only downside of this RP is that it makes doc generation slower because the non public docs are also built. If that's the case, I think that's a fine change.

Let's see what @trefis says about this.

**Comment by trefis** [comment]
> Am I correct to state that the private libraries will not be included in the top level generated index?

I think that's correct.

The change looks fine to me.

**Comment by MiloDavis** [comment]
Could you merge this? We're currently using the dev version of jbuilder for Tezos and this would help us out a lot with generating documentation for some new people. If not, let me know if there are changes I can make to help facilitate this getting merged.

**Comment by rgrinberg** [comment]
Milo, have you filled out the janestreet CLA? If so then this PR is lgtm

**Comment by MiloDavis** [comment]
@rgrinberg Is it the core cla or is there a jbuilder specific one? As of a few minutes ago, I've sent in the one for core as specified [here](https://janestreet.github.io/contributing.html).

**Comment by rgrinberg** [comment]
Signing one is sufficient I believe. Also, I don't have a list of people who have signed the CLA so I also have to double check.

I'm merging and if there are some CLA objections from JST employees. we can revert.

**Comment by trefis** [comment]
(Just to confirm: Milo signed the CLA)

**Pull request merged**
