### PR TITLE
Replace the S-expression Parser by Usexp

### LINKED ISSUE #335: Change the sexp parser
Quoting diml:

> 1.0 is change the sexp parser. The doc says that it follows the sexplib/parsexp conventions but in fact it doesn't. I quickly hacked a lexer-based sexp parser at the beginning, but it's surprisingly hard to write a correct one using regexps, at least for the specific format we are using in JS code. And the printer is broken as well, it doesn't quote atoms properly. It's only for corner cases, so it probably doesn't affect any existing packages, but if we wait too long it could be a cause of pain in the future. Especially if people write higher-level tools to work with jbuild files. We can't just vendor
parsexp as it's too big, but there are things we can do to share the important part of the code.

### PR DESCRIPTION
**Pull request by diml**
This PR vendors https://github.com/janestreet/usexp and use to replace the S-expression parser and printer.

The bootstrap had to be updated to support wrapped libraries.

Fixes #335

### CODE REVIEW

**Comment by rgrinberg** [comment]
@bobot one point might be that it will be useful as a part of configurator as well. Which we are also planning to include as part of jbuilder.

**Comment by rgrinberg** [comment]
I can't reproduce that travis failure so I've restarted the build.

**Comment by rgrinberg** [comment]
I actually have the reverse question, do we really need the other original source repository? usexp was created specifically for dune, it should be easy enough to handle whatever few issues users come up in this repo. But in any case, this PR looks good and everything passes.

@bobot I'd like to merge unless you object soon.

**Comment by rgrinberg** [comment]
https://github.com/janestreet/usexp

**Comment by diml** [comment]
I think the original repository will end up not being only for jbuilder. I didn't take the time to write a proper readme, etc...

**Pull request merged**
