### PR TITLE
Cross Compilation

### PR DESCRIPTION
**Pull request by rgrinberg**
cc @diml @toots @whitequark

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've resolved the conflicts with master.

**Comment by rgrinberg** [comment]
@diml If I understand your new proposal correctly, then cross compilation will directly depend on findlib. That doesn't seem to be desirable to me, especially that the only thing we need to distinguish the toolchains is a directory prefix argument. Before we used a different opam switch to do that, I agree that's not ideal. But why not just ask the user to provide the host root directly rather than doing it through findlib.

**Comment by diml** [comment]
We are really just reading a configuration file, currently we only use the ocamlfind binary to locate the configuration file.

If there are other way to do cross-compilation later, we'll see what we do. We can always extend the syntax to allow other way of setting up cross-compilation. I imagine that at some point the tooling will officially support cross-compilation and that the work done in the various projects to provide cross-compilation will be somehow integrated upstream. At this point will update jbuilder to support the official way.

**Comment by rgrinberg** [comment]
OK, well I'm ok with it as long as we aren't committed to using findlib here. I thought that namespaces will make findlib completely optional, so I'd hate the introduce the dependence on it in a backdoor way later.

**Comment by diml** [comment]
BTW, we don't need to specify too much how things work in the doc. Let's just say that for now we support cross-compilation using the opam-cross-* repositories and that users who want to use `opam-cross-x` should pass `-x x` to jbuilder or write `(targets (x))` in their `jbuild-workspace` file. We don't need to talk about findlib, it's an implementation detail

**Comment by rgrinberg** [comment]
@toots would you mind trying this branch and see if it works for you?

**Comment by rgrinberg** [comment]
> We don't need to talk about findlib, it's an implementation detail

Do we mention that a target corresponds to a findlib toolchain? Otherwise this term doesn't really mean much.

**Comment by toots** [comment]
@rgrinberg has the command-line syntax changed besides removing `--install-prefix` ? I'm getting this:
```
[sexplib-windows: jbuilder-windows build] Command started
+ jbuilder-windows "build" "-p" "sexplib" "-j" "4" "-x" "windows" (CWD=/home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2)
- Error: exception Sys_error("Is a directory")
- Backtrace:
- Raised by primitive operation at file "pervasives.ml", line 384, characters 7-32
- Called from file "lexing.ml", line 86, characters 4-49
- Called from file "src/meta_lexer.ml", line 275, characters 25-57
- Called from file "src/meta_lexer.ml" (inlined), line 201, characters 4-34
- Called from file "src/meta.ml", line 75, characters 10-17
- Called from file "src/import.ml", line 469, characters 8-11
- Re-raised at file "src/import.ml", line 471, characters 30-37
- Called from file "src/findlib.ml", line 134, characters 33-64
- Called from file "src/context.ml", line 207, characters 12-63
- Called from file "src/future.ml", line 88, characters 40-45
- Called from file "src/future.ml", line 83, characters 65-70
- Called from file "src/future.ml", line 37, characters 9-12
- Re-raised at file "src/future.ml", line 17, characters 36-47
- Called from file "src/future.ml", line 40, characters 9-23
- Called from file "src/import.ml", line 469, characters 8-11
- Re-raised at file "src/import.ml", line 471, characters 30-37
- Called from file "src/future.ml", line 37, characters 9-12
- Re-raised at file "src/future.ml", line 17, characters 36-47
- Called from file "src/future.ml", line 40, characters 9-23
- Called from file "src/import.ml", line 469, characters 8-11
- Re-raised at file "src/import.ml", line 471, characters 30-37
- Called from file "src/future.ml", line 37, characters 9-12
- Re-raised at file "src/future.ml", line 17, characters 36-47
- Called from file "src/future.ml", line 40, characters 9-23
- Called from file "src/import.ml", line 469, characters 8-11
- Re-raised at file "src/import.ml", line 471, characters 30-37
- Called from file "src/future.ml", line 703, characters 6-29
- Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
- Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
- Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
- Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
- Called from file "bin/main.ml", line 1089, characters 10-51
[ERROR] The compilation of sexplib-windows failed at "jbuilder-windows build -p sexplib -j 4 -x windows".
```

**Comment by diml** [comment]
Ah, my mistake, I pushed a fix

**Comment by toots** [comment]
Thanks! Got a new problem now..

```
[sexplib-windows: jbuilder-windows build] Command started
+ jbuilder-windows "build" "-p" "sexplib" "-j" "4" "-x" "windows" (CWD=/home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2)
- Multiple rules generated for num/lib/.merlin
[ERROR] The compilation of sexplib-windows failed at "jbuilder-windows build -p sexplib -j 4 -x windows".

#=== ERROR while installing sexplib-windows.v0.9.2 ============================#
# opam-version 1.2.2
# os           linux
# command      jbuilder-windows build -p sexplib -j 4 -x windows
# path         /home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2
# compiler     4.04.0+32bit
# exit-code    1
# env-file     /home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2/sexplib-windows-22-8c0dd3.env
# stdout-file  /home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2/sexplib-windows-22-8c0dd3.out
# stderr-file  /home/opam/.opam/4.04.0+32bit/build/sexplib-windows.v0.9.2/sexplib-windows-22-8c0dd3.err
### stderr ###
# Multiple rules generated for num/lib/.merlin
```

Not sure what this is about. Let me know if you need steps to reproduce.

**Comment by diml** [comment]
I haven't managed to install mingw-w64 on my box, so it's hard to try. I need to add some fake cross-compilation test

**Comment by toots** [comment]
@diml We have a docker-based test suite that you should be able to tap in for quick testing. I've pushed the branch with the changes here: https://github.com/ocaml-cross/opam-cross-windows/pull/56

**Comment by diml** [comment]
Ah! Thanks, but I don't have docker either at work :(

I'll try with tests, it's good to have tests anyway

**Comment by diml** [comment]
Ok, I added a test and fixed some problems. The PR should be in a better state now.

**Comment by toots** [comment]
Yeah it's looking good from here as well. Thanks!

**Comment by toots** [comment]
Actually, I've got another issue now here when compiling `ocaml-migrate-parsetree-windows`:
```
### stderr ###
# Warning 58: no cmx file was found in path for module Config, and its interface was not compiled with -opaque
# [...]
#     ocamlopt src/gen/gen.exe [default.windows]
# Error: exception Invalid_argument("index out of bounds")
# Backtrace:
# Raised by primitive operation at file "src/path.ml", line 192, characters 29-39
# Called from file "src/action.ml", line 543, characters 13-62
# Called from file "src/action.ml", line 550, characters 5-54
# Called from file "src/build_system.ml", line 518, characters 6-82
# Called from file "src/future.ml", line 83, characters 65-70
# Called from file "src/future.ml", line 37, characters 9-12
```

**Comment by diml** [comment]
Superseeded by #380

**Pull request closed without merging**
